name: Make release

# Required secrets:
# GITHUB_PAT - GitHub personal access token with permissions to make commits to repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version in SemVer (e.g. '0.5.0')
        required: true

jobs:
  make-release:
    name: Make release
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout Capact repository
        uses: actions/checkout@v2
        with:
          repository: "capactio/capact"
          ref: "v${{ github.event.inputs.version }}"
          path: "../capact"
      - name: Setup Git credentials
        # Replacing the GH Action token with PAT is required to trigger the branch-build workflow on a commit:
        # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
        run: |
          git remote remove origin
          git remote add origin https://${{secrets.GITHUB_PAT}}@github.com/${{github.repository}}.git
          git config --global user.email "bot@capact.io"
          git config --global user.name "Capact Bot"
      - name: Synchronize CLI documentation
        run: npm run sync-cli-docs
      - name: Release
        run: |
